defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag

exclude:
    - start.sh

future: true
strict_front_matter: true
livereload: true
open_url: true
